/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.IngredienteJpaController;
import controladores.Miscelanea;
import controladores.RecetaJpaController;
import entidades.ChildWindow;
import entidades.Ingrediente;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author venganzaalchocolate
 */
public class BuscarIngrediente extends ChildWindow {

    IngredienteJpaController controladorIngrediente = new IngredienteJpaController(Miscelanea.getEntityManager());
    List<Ingrediente> listaBusqueda;

    /**
     * Creates new form buscarIngrediente
     */
    // buscarIngrediente es hija de paginaLista, extends ChildWindows, de esta manera cuando se cierre paginaLista carga los datos de los ingredientes autómaticamente
    public BuscarIngrediente(PaginaLista mainWindow, String windowName) {
        super(mainWindow, windowName);
        initComponents();
        listaBusqueda = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        atras = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        botonCrearIngrediente = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        botonEliminarIngrediente = new javax.swing.JButton();
        botonaddIng = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atras.setBackground(new java.awt.Color(252, 167, 46));
        atras.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("<-");
        atras.setBorderPainted(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 70, 50));

        jTextField1.setBackground(new java.awt.Color(238, 244, 238));
        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 153));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jTextField1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextField1.setSelectionColor(new java.awt.Color(0, 102, 153));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 490, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jScrollPane1.setForeground(new java.awt.Color(0, 102, 153));

        jList1.setBackground(new java.awt.Color(238, 244, 238));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jList1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 510, 210));

        botonCrearIngrediente.setBackground(new java.awt.Color(179, 57, 170));
        botonCrearIngrediente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonCrearIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        botonCrearIngrediente.setText("crear");
        botonCrearIngrediente.setActionCommand("crear");
        botonCrearIngrediente.setBorderPainted(false);
        botonCrearIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearIngredienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 90, 50));

        buscar.setBackground(new java.awt.Color(252, 167, 46));
        buscar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar");
        buscar.setBorderPainted(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, 50));

        botonEliminarIngrediente.setBackground(new java.awt.Color(252, 167, 46));
        botonEliminarIngrediente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonEliminarIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarIngrediente.setText("eliminar");
        botonEliminarIngrediente.setBorderPainted(false);
        botonEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarIngredienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 120, 50));

        botonaddIng.setBackground(new java.awt.Color(179, 57, 170));
        botonaddIng.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonaddIng.setForeground(new java.awt.Color(255, 255, 255));
        botonaddIng.setText("Añadir");
        botonaddIng.setBorderPainted(false);
        botonaddIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonaddIngActionPerformed(evt);
            }
        });
        jPanel1.add(botonaddIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        cargarIngredientes();
    }//GEN-LAST:event_buscarActionPerformed

    // cargar ingredientes, método que busca coincidencias, si no se escibe nada te muestra todos los ingredientes
    private void cargarIngredientes() {
        jList1.setSelectedIndex(-1);
        listaBusqueda = controladorIngrediente.findIngredienteEntities().stream().filter((t) -> t.getNombreIngrediente().contains(jTextField1.getText().toLowerCase())).toList();
        String[] listaIngredientesString = listaBusqueda.stream().map((t) -> t.getNombreIngrediente()).toList().toArray(new String[listaBusqueda.size()]);
        jList1.setListData(listaIngredientesString);

    }

   
    private void botonaddIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonaddIngActionPerformed
        int index = jList1.getAnchorSelectionIndex();
        jList1.setSelectedIndex(-1);
        int confirmacion =-1 ;
        if (index != -1
                && !PaginaLista.listaIngredientes.contains(listaBusqueda.get(index))) {
            confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que deseas añadir el ingrediente %s".formatted(listaBusqueda.get(index).getNombreIngrediente()));
            if (confirmacion == 0) {
                try {
                    PaginaLista.listaCantidades.add(pedirCantidad());
                    PaginaLista.listaIngredientes.add(listaBusqueda.get(index));
                    JOptionPane.showMessageDialog(null, "Se ha añadido el ingrediente correctamente");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se ha podido borrar añadir el ingrediente %s".formatted(e));
                }
            } else  {
            JOptionPane.showMessageDialog(null, "No se ha añadido el ingrediente");
            }
        } else if (index == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un ingrediente");
        } else {
            JOptionPane.showMessageDialog(null, "La receta ya tiene ese ingrediente");
        }
    }//GEN-LAST:event_botonaddIngActionPerformed

    // método que pide la cantidad del ingrediente, si no se le pasa un entero salta un mensaje y vuelve a pedirte la cantidad
    private int pedirCantidad() {
        boolean condicion = true;
        do {
            try {
                String cantidad = JOptionPane.showInputDialog("Cantidad ?");
                int cantidadI = Integer.parseInt(cantidad);
                condicion = false;
                return cantidadI;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Debes poner un número entero");
            }
        } while (condicion);
        return 0;
    }

    private void botonCrearIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearIngredienteActionPerformed
        CrearIngrediente ventanaIngrediente = new CrearIngrediente();
        ventanaIngrediente.pack();
        ventanaIngrediente.setLocationRelativeTo(null);
        ventanaIngrediente.setVisible(true);
    }//GEN-LAST:event_botonCrearIngredienteActionPerformed

    // elimina un ingrediente siempre y cuando no esté asociado a una receta
    private void botonEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarIngredienteActionPerformed
        int index = jList1.getAnchorSelectionIndex();
        if (index != -1
                && JOptionPane.showConfirmDialog(null, "Seguro que deseas borrar el ingrediente %s".formatted(listaBusqueda.get(index).getNombreIngrediente())) == 0) {
            try {
                controladorIngrediente.destroy(listaBusqueda.get(index).getCodIngrediente());
                cargarIngredientes();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se ha podido borrar el ingrediente, ya que existe una receta con ese ingrediente");
            }
        }
    }//GEN-LAST:event_botonEliminarIngredienteActionPerformed

    // cierra ventana
    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton botonCrearIngrediente;
    private javax.swing.JButton botonEliminarIngrediente;
    private javax.swing.JButton botonaddIng;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
