/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.IngredienteJpaController;
import controladores.Miscelanea;
import controladores.RecetaJpaController;
import entidades.ChildWindow;
import entidades.Ingrediente;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author venganzaalchocolate
 */
public class BuscarIngrediente extends ChildWindow {

    IngredienteJpaController controladorIngrediente = new IngredienteJpaController(Miscelanea.getEntityManager());
    List<Ingrediente> listaBusqueda;

    /**
     * Creates new form buscarIngrediente
     */
    public BuscarIngrediente(PaginaLista mainWindow, String windowName) {
        super(mainWindow, windowName);
        initComponents();
        listaBusqueda = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonLista5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        botonLista1 = new javax.swing.JButton();
        botonLista2 = new javax.swing.JButton();
        botonLista4 = new javax.swing.JButton();
        botonLista3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonLista5.setBackground(new java.awt.Color(252, 167, 46));
        botonLista5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonLista5.setForeground(new java.awt.Color(255, 255, 255));
        botonLista5.setText("<-");
        botonLista5.setBorderPainted(false);
        botonLista5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista5ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 70, 50));

        jTextField1.setBackground(new java.awt.Color(238, 244, 238));
        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 153));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jTextField1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextField1.setSelectionColor(new java.awt.Color(0, 102, 153));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 490, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jScrollPane1.setForeground(new java.awt.Color(0, 102, 153));

        jList1.setBackground(new java.awt.Color(238, 244, 238));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jList1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 510, 210));

        botonLista1.setBackground(new java.awt.Color(179, 57, 170));
        botonLista1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonLista1.setForeground(new java.awt.Color(255, 255, 255));
        botonLista1.setText("+");
        botonLista1.setActionCommand("crear");
        botonLista1.setBorderPainted(false);
        botonLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 60, 50));

        botonLista2.setBackground(new java.awt.Color(252, 167, 46));
        botonLista2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonLista2.setForeground(new java.awt.Color(255, 255, 255));
        botonLista2.setText("Buscar");
        botonLista2.setBorderPainted(false);
        botonLista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 140, 50));

        botonLista4.setBackground(new java.awt.Color(252, 167, 46));
        botonLista4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonLista4.setForeground(new java.awt.Color(255, 255, 255));
        botonLista4.setText("-");
        botonLista4.setBorderPainted(false);
        botonLista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista4ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 60, 50));

        botonLista3.setBackground(new java.awt.Color(179, 57, 170));
        botonLista3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonLista3.setForeground(new java.awt.Color(255, 255, 255));
        botonLista3.setText("Añadir");
        botonLista3.setBorderPainted(false);
        botonLista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista2ActionPerformed
        cargarIngredientes();
    }//GEN-LAST:event_botonLista2ActionPerformed

    private void cargarIngredientes() {
        jList1.setSelectedIndex(-1);
        listaBusqueda = controladorIngrediente.findIngredienteEntities().stream().filter((t) -> t.getNombreIngrediente().contains(jTextField1.getText().toLowerCase())).toList();
        String[] listaIngredientesString = listaBusqueda.stream().map((t) -> t.getNombreIngrediente()).toList().toArray(new String[listaBusqueda.size()]);
        jList1.setListData(listaIngredientesString);

    }

    private void botonLista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista3ActionPerformed
        int index = jList1.getAnchorSelectionIndex();
        jList1.setSelectedIndex(-1);
        int confirmacion =-1 ;
        if (index != -1
                && !PaginaLista.listaIngredientes.contains(listaBusqueda.get(index))) {
            confirmacion = JOptionPane.showConfirmDialog(null, "Seguro que deseas añadir el ingrediente %s".formatted(listaBusqueda.get(index).getNombreIngrediente()));
            if (confirmacion == 0) {
                try {
                    PaginaLista.listaCantidades.add(pedirCantidad());
                    PaginaLista.listaIngredientes.add(listaBusqueda.get(index));
                    JOptionPane.showMessageDialog(null, "Se ha añadido el ingrediente correctamente");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se ha podido borrar añadir el ingrediente %s".formatted(e));
                }
            } else  {
            JOptionPane.showMessageDialog(null, "No se ha añadido el ingrediente");
            }
        } else if (index == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un ingrediente");
        } else {
            JOptionPane.showMessageDialog(null, "La receta ya tiene ese ingrediente");
        }
    }//GEN-LAST:event_botonLista3ActionPerformed

    private int pedirCantidad() {
        boolean condicion = true;
        do {
            try {
                String cantidad = JOptionPane.showInputDialog("Cantidad ?");
                int cantidadI = Integer.parseInt(cantidad);
                condicion = false;
                return cantidadI;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Debes poner un número entero");
            }
        } while (condicion);
        return 0;
    }

    private void botonLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista1ActionPerformed
        CrearIngrediente ventanaIngrediente = new CrearIngrediente();
        ventanaIngrediente.pack();
        ventanaIngrediente.setLocationRelativeTo(null);
        ventanaIngrediente.setVisible(true);
    }//GEN-LAST:event_botonLista1ActionPerformed

    private void botonLista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista4ActionPerformed
        int index = jList1.getAnchorSelectionIndex();
        if (index != -1
                && JOptionPane.showConfirmDialog(null, "Seguro que deseas borrar el ingrediente %s".formatted(listaBusqueda.get(index).getNombreIngrediente())) == 0) {
            try {
                controladorIngrediente.destroy(listaBusqueda.get(index).getCodIngrediente());
                cargarIngredientes();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se ha podido borrar el ingrediente %s".formatted(e));
            }
        }
    }//GEN-LAST:event_botonLista4ActionPerformed

    private void botonLista5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista5ActionPerformed
        dispose();
    }//GEN-LAST:event_botonLista5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLista1;
    private javax.swing.JButton botonLista2;
    private javax.swing.JButton botonLista3;
    private javax.swing.JButton botonLista4;
    private javax.swing.JButton botonLista5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
