/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.IngredienteJpaController;
import controladores.Miscelanea;
import entidades.Ingrediente;
import javax.swing.JOptionPane;

/**
 *
 * @author venganzaalchocolate
 */
public class CrearIngrediente extends javax.swing.JFrame {

    IngredienteJpaController controladorIngrediente = new IngredienteJpaController(Miscelanea.getEntityManager());

    /**
     * Creates new form buscarIngrediente
     */
    public CrearIngrediente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        crearIngrediente = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(238, 244, 238));
        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 153));
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jTextField1.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jTextField1.setSelectionColor(new java.awt.Color(0, 102, 153));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 490, 40));

        crearIngrediente.setBackground(new java.awt.Color(179, 57, 170));
        crearIngrediente.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        crearIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        crearIngrediente.setText("Añadir");
        crearIngrediente.setBorderPainted(false);
        crearIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearIngredienteActionPerformed(evt);
            }
        });
        jPanel1.add(crearIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 130, 50));

        atras.setBackground(new java.awt.Color(252, 167, 46));
        atras.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("<-");
        atras.setBorderPainted(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 70, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearIngrediente.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // crea un ingrediente siempre que no exista
    private void crearIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearIngredienteActionPerformed
        String nombre = jTextField1.getText();
        if (!nombre.isBlank()) {
            try {
                // se usa una namedQuery
                controladorIngrediente.findByNombreIngrediente(nombre.toLowerCase());
                JOptionPane.showMessageDialog(null, "El ingrediente ya existe.");
            } catch (Exception e) {
                if (JOptionPane.showConfirmDialog(null, "Seguro que deseas crear el ingrediente %s".formatted(nombre.toLowerCase())) == 0) {
                    controladorIngrediente.create(new Ingrediente(nombre.toLowerCase()));
                }
            }
        }  else {
        JOptionPane.showMessageDialog(null, "No puedes dejar el nombre del ingrediente en blanco");
        }
    }//GEN-LAST:event_crearIngredienteActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        dispose();
    }//GEN-LAST:event_atrasActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton crearIngrediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
