/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;


import controladores.Miscelanea;
import controladores.UsuarioJpaController;
import entidades.Usuario;
import javax.swing.JOptionPane;


/**
 *
 * @author venganzaalchocolate
 */
public class CrearUsuario extends javax.swing.JFrame {

    UsuarioJpaController controladorUsuario = new UsuarioJpaController(Miscelanea.getEntityManager());

    /**
     * Creates new form buscarIngrediente
     */
    public CrearUsuario() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonLista5 = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        nombres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        botonLista4 = new javax.swing.JButton();
        botonLista3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(576, 499));
        setResizable(false);
        setSize(new java.awt.Dimension(576, 499));

        jPanel1.setMinimumSize(new java.awt.Dimension(576, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(576, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonLista5.setBackground(new java.awt.Color(252, 167, 46));
        botonLista5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        botonLista5.setForeground(new java.awt.Color(255, 255, 255));
        botonLista5.setText("<-");
        botonLista5.setBorderPainted(false);
        botonLista5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista5ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 70, 50));

        nombre.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(26, 150, 138));
        nombre.setText("Usuario");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 30));

        nombre1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        nombre1.setForeground(new java.awt.Color(26, 150, 138));
        nombre1.setText("Email");
        jPanel1.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, 30));

        email.setBackground(new java.awt.Color(238, 244, 238));
        email.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(0, 102, 153));
        email.setText("text@text.com");
        email.setToolTipText("");
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 30));

        nombres.setBackground(new java.awt.Color(238, 244, 238));
        nombres.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        nombres.setForeground(new java.awt.Color(0, 102, 153));
        nombres.setText("...");
        nombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jPanel1.add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 320, 30));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jScrollPane1.setForeground(new java.awt.Color(0, 102, 153));

        jList1.setBackground(new java.awt.Color(238, 244, 238));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jList1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, 270));

        botonLista4.setBackground(new java.awt.Color(252, 167, 46));
        botonLista4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonLista4.setForeground(new java.awt.Color(255, 255, 255));
        botonLista4.setText("Reset");
        botonLista4.setBorderPainted(false);
        botonLista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista4ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 100, 50));

        botonLista3.setBackground(new java.awt.Color(179, 57, 170));
        botonLista3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        botonLista3.setForeground(new java.awt.Color(255, 255, 255));
        botonLista3.setText("Aceptar");
        botonLista3.setBorderPainted(false);
        botonLista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLista3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonLista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CrearUsuario.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonLista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista3ActionPerformed

        if (nombres.getText().isBlank() || email.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
        } else {
            String tmp =
                    """
                    Esta seguro de querer crear el usuario: 
                    %s 
                    %s
                    """.formatted(nombres.getText(), email.getText());
            boolean coincidencia = controladorUsuario.findUsuarioEntities().stream().anyMatch((t)
                    -> t.getNombre().equalsIgnoreCase(nombres.getText())
                    && t.getEmail().equalsIgnoreCase(t.getEmail()));
            if (!coincidencia
                    && JOptionPane.showConfirmDialog(null, tmp) == 0) {
                try {
                    controladorUsuario.create(new Usuario(nombres.getText(), email.getText()));
                    JOptionPane.showMessageDialog(null, "Usuario creado correctamente");
                    SeleccionarUsuario seleccionar = new SeleccionarUsuario();
                    seleccionar.pack();
                    seleccionar.setLocationRelativeTo(null);
                    seleccionar.setVisible(true);
                    dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se ha podido crear el usuario");
                    System.out.println(e);
                }
            } else if (coincidencia) {
                JOptionPane.showMessageDialog(null, "Ese usuario ya existe");
            }
        }
    }//GEN-LAST:event_botonLista3ActionPerformed

    private void botonLista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista4ActionPerformed
        nombres.setText("");
        email.setText("");
    }//GEN-LAST:event_botonLista4ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void botonLista5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLista5ActionPerformed
        SeleccionarUsuario seleccionar = new SeleccionarUsuario();
        seleccionar.pack();
        seleccionar.setLocationRelativeTo(null);
        seleccionar.setVisible(true);

        dispose();
    }//GEN-LAST:event_botonLista5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLista3;
    private javax.swing.JButton botonLista4;
    private javax.swing.JButton botonLista5;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JTextField nombres;
    // End of variables declaration//GEN-END:variables
}
