/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.CantidadJpaController;
import controladores.IngredienteJpaController;
import controladores.Miscelanea;
import controladores.RecetaJpaController;
import controladores.UsuarioJpaController;
import entidades.Cantidad;
import entidades.ChildWindow;
import entidades.Ingrediente;
import entidades.Receta;
import entidades.Usuario;
import java.awt.event.WindowEvent;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import recetario.Recetario;

/**
 *
 * @author venganzaalchocolate
 */
public class SeleccionarUsuario extends javax.swing.JFrame {

    UsuarioJpaController controladorUsuario = new UsuarioJpaController(Miscelanea.getEntityManager());
    RecetaJpaController controladorReceta = new RecetaJpaController(Miscelanea.getEntityManager());
    CantidadJpaController controladorCantidad = new CantidadJpaController(Miscelanea.getEntityManager());
    IngredienteJpaController controladorIngrediente = new IngredienteJpaController(Miscelanea.getEntityManager());
    List<Usuario> listaBusqueda;
    List<Receta> listaRecetas;

    /**
     * Creates new form buscarIngrediente
     */
    public SeleccionarUsuario() {
        listaBusqueda = new ArrayList<>();
        listaRecetas = new ArrayList<>();
        initComponents();
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        crearUsuario = new javax.swing.JButton();
        eliminarUsuario = new javax.swing.JButton();
        aceptarUsuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(576, 499));
        setPreferredSize(new java.awt.Dimension(576, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(576, 499));

        jPanel1.setMinimumSize(new java.awt.Dimension(576, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(576, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jScrollPane1.setForeground(new java.awt.Color(0, 102, 153));

        jList1.setBackground(new java.awt.Color(238, 244, 238));
        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 244, 238)));
        jList1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, 270));

        crearUsuario.setBackground(new java.awt.Color(179, 57, 170));
        crearUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        crearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        crearUsuario.setText("+");
        crearUsuario.setActionCommand("crear");
        crearUsuario.setBorderPainted(false);
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 60, 50));

        eliminarUsuario.setBackground(new java.awt.Color(252, 167, 46));
        eliminarUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        eliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        eliminarUsuario.setText("-");
        eliminarUsuario.setBorderPainted(false);
        eliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 60, 50));

        aceptarUsuario.setBackground(new java.awt.Color(179, 57, 170));
        aceptarUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        aceptarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        aceptarUsuario.setText("Aceptar");
        aceptarUsuario.setBorderPainted(false);
        aceptarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(aceptarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seleccionarUsuario.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarUsuarios() {
        jList1.setSelectedIndex(-1);
        listaBusqueda = controladorUsuario.findUsuarioEntities();
        String[] listaIngredientesString = listaBusqueda.stream().map((t) -> "%s".formatted(t.getNombre())).toList().toArray(new String[listaBusqueda.size()]);
        jList1.setListData(listaIngredientesString);

    }

    private void aceptarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarUsuarioActionPerformed
        int index = jList1.getAnchorSelectionIndex();
        jList1.setSelectedIndex(-1);
        if (index != -1) {
            try {
                // cuando seleccinamos un usuario modificamos la variable estática del main para que paginaLista tenga acceso
                Recetario.usuario = listaBusqueda.get(index);
            } catch ( ArrayIndexOutOfBoundsException e) {
                System.out.println(e);
            }
            
            Portada portada = new Portada();
            portada.pack();
            portada.setLocationRelativeTo(null);
            portada.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un usuario");
        }
    }//GEN-LAST:event_aceptarUsuarioActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        CrearUsuario crearUsuario = new CrearUsuario();
        crearUsuario.pack();
        crearUsuario.setLocationRelativeTo(null);
        crearUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_crearUsuarioActionPerformed

// si eliminamos un usuario eliminamos todas las recetas asociadas
    private void eliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuarioActionPerformed
        int index = jList1.getAnchorSelectionIndex();
        jList1.setSelectedIndex(-1);
        jList1.clearSelection();
        if (index != -1
                && JOptionPane.showConfirmDialog(null, "Seguro que deseas borrar el usuario %s, esto eliminará todas sus recetas".formatted(listaBusqueda.get(index).getNombre())) == 0) {
            try {
                listaRecetas = controladorReceta.findRecetaEntities();
                List<Receta> recetasCreador = listaRecetas.stream().filter((t) -> t.getCreador().equals(listaBusqueda.get(index))).toList();
                for (Receta receta : recetasCreador) {
                    try {
                        for (int i = 0; i < receta.getCantidadList().size(); i++) {
                            Cantidad get = receta.getCantidadList().get(i);
                            controladorCantidad.destroy(get.getCantidadPK());
                        }
                        controladorReceta.destroy(receta.getCodReceta());
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "No se ha podido borrar la receta, %s".formatted(e));
                    }
                }
                controladorUsuario.destroy(listaBusqueda.get(index).getCodUsuario());
                cargarUsuarios();
                Recetario.usuario=new Usuario();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se ha podido borrar el usuario %s".formatted(e));
            }
        }
    }//GEN-LAST:event_eliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarUsuario;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JButton eliminarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
